/**
 * @file main.h
 * @brief Board specific define values
 *
 * That file is generated by STM32CubeMX package and contains Board specific
 * defines that might be used in a Board Specific Package sources or adapters
 */
#ifndef __MAIN_H
#define __MAIN_H

/** \defgroup BSP (Board Support Package)
  * @{
  */

/// \brief Button 1 GPIO Pin definition
#define B1_Pin GPIO_PIN_13
/// \brief Button 1 GPIO Port definition
#define B1_GPIO_Port GPIOC
/// \brief USART TX Pin definition
#define USART_TX_Pin GPIO_PIN_2
/// \brief USART TX Port definition
#define USART_TX_GPIO_Port GPIOA
/// \brief USART RX Pin definition
#define USART_RX_Pin GPIO_PIN_3
/// \brief USART RX Port definition
#define USART_RX_GPIO_Port GPIOA
/// \brief Green LED (LD2) pin definition
#define LD2_Pin GPIO_PIN_5
/// \brief Green LED (LD2) port definition
#define LD2_GPIO_Port GPIOA
#define TMS_Pin GPIO_PIN_13
#define TMS_GPIO_Port GPIOA
#define TCK_Pin GPIO_PIN_14
#define TCK_GPIO_Port GPIOA
#define SWO_Pin GPIO_PIN_3
#define SWO_GPIO_Port GPIOB

/**
  * @}
  */

#endif /* __MAIN_H */
